name: Continuous Integration

on:
  push:

  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    name: 'Build'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20', '22', '24']

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm run build
      - run: npm run lint
